import { useCallback, useEffect, useRef, useState } from 'react';
import { api, authStore, API_BASE_URL } from './services/api';

const navItems = [['dashboard', 'Dashboard'], ['workspaces', 'Workspaces'], ['shared', 'Shared files'], ['profile', 'Profile & settings']];
const formatBytes = (bytes = 0) => bytes < 1024 ? `${bytes} B` : bytes < 1048576 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1048576).toFixed(1)} MB`;
const formatDate = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) : '—';

function useAsync(task, dependencies = []) {
  const [state, setState] = useState({ loading: true, data: null, error: '' });
  const run = useCallback(async () => {
    setState((old) => ({ ...old, loading: true, error: '' }));
    try { setState({ loading: false, data: await task(), error: '' }); }
    catch (error) { setState({ loading: false, data: null, error: error.message }); }
  }, dependencies);
  useEffect(() => { run(); }, [run]);
  return { ...state, reload: run };
}

function AuthScreen({ onAuthenticated, oauthError }) {
  const [mode, setMode] = useState('login');
  const [form, setForm] = useState({ email: '', password: '', username: '', full_name: '', challenge: '', otp: '', reset_token: '', new_password: '' });
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event) => {
    event.preventDefault(); setError(''); setLoading(true);
    try {
      if (mode === 'register') { await api.register(form); setMode('login'); setError('Account created. Sign in to continue.'); }
      else if (mode === 'forgot') { await api.forgotPassword({ email: form.email }); setMode('verify'); setError('If an account exists, a reset code was sent.'); }
      else if (mode === 'verify') { const result = await api.verifyResetOtp({ challenge: form.challenge, otp: form.otp }); setForm({ ...form, reset_token: result.reset_token }); setMode('reset'); setError('Code verified. Choose a new password.'); }
      else if (mode === 'reset') { await api.resetPassword({ reset_token: form.reset_token, new_password: form.new_password }); setMode('login'); setForm({ ...form, password: '', new_password: '' }); setError('Password reset. Sign in to continue.'); }
      else { const tokens = await api.login({ email: form.email, password: form.password }); authStore.set(tokens); onAuthenticated(); }
    } catch (err) { setError(err.message); } finally { setLoading(false); }
  };
    const resetMode = ['forgot', 'verify', 'reset'].includes(mode);
    return <main className="auth-shell"><section className="auth-intro"><div className="brand"><span>✦</span> AETHERA</div><div><p className="eyebrow">PRIVATE BY DESIGN</p><h1>Your work,<br />calmly organized.</h1><p>Secure, intelligent storage and collaboration for the things that matter.</p></div><div className="intro-card"><span>◈</span><p>One place for your documents, projects, and shared workspaces.</p></div></section><section className="auth-panel"><form onSubmit={submit} className="auth-card"><p className="eyebrow">WELCOME TO AETHERA</p><h2>{mode === 'login' ? 'Sign in' : mode === 'register' ? 'Create your account' : mode === 'forgot' ? 'Reset your password' : mode === 'verify' ? 'Enter your code' : 'Choose a new password'}</h2><p className="muted">{mode === 'login' ? 'Continue to your secure workspace.' : 'Secure account recovery for AETHERA.'}</p>{(oauthError || error) && <div className="notice">{oauthError || error}</div>}
      {['login', 'register', 'forgot'].includes(mode) && <Field label="Email address" type="email" value={form.email} onChange={(email) => setForm({ ...form, email })} required />}
      {mode === 'register' && <><Field label="Full name" value={form.full_name} onChange={(full_name) => setForm({ ...form, full_name })} required /><Field label="Username" value={form.username} onChange={(username) => setForm({ ...form, username })} required /><Field label="Password" type="password" value={form.password} onChange={(password) => setForm({ ...form, password })} required minLength={8} /></>}
      {mode === 'login' && <Field label="Password" type="password" value={form.password} onChange={(password) => setForm({ ...form, password })} required minLength={1} />}
      {mode === 'verify' && <><Field label="Reset challenge" value={form.challenge} onChange={(challenge) => setForm({ ...form, challenge })} required /><Field label="6-digit code" inputMode="numeric" value={form.otp} onChange={(otp) => setForm({ ...form, otp })} required /></>}
      {mode === 'reset' && <Field label="New password" type="password" value={form.new_password} onChange={(new_password) => setForm({ ...form, new_password })} required minLength={8} />}
      <button className="button primary" disabled={loading}>{loading ? 'Please wait…' : mode === 'login' ? 'Sign in' : mode === 'register' ? 'Create account' : mode === 'forgot' ? 'Send reset code' : mode === 'verify' ? 'Verify code' : 'Reset password'}</button>
      {mode === 'login' && <><div className="divider"><span>or</span></div><a className="button google" href={`${API_BASE_URL}/auth/google/login`}><b>G</b> Continue with Google</a><p className="switch"><button type="button" onClick={() => { setMode('forgot'); setError(''); }}>Forgot password?</button></p></>}
      <p className="switch"><button type="button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'login' ? 'Create an account' : 'Back to sign in'}</button></p></form></section></main>;
}

function Field({ label, onChange, ...props }) { return <label className="field"><span>{label}</span><input onChange={(e) => onChange(e.target.value)} {...props} /></label>; }
function Empty({ title, body, action }) { return <div className="empty"><div>◇</div><h3>{title}</h3><p>{body}</p>{action}</div>; }
function ErrorState({ message, retry }) { return <div className="notice"><b>Couldn’t load this view.</b><br />{message} {retry && <button onClick={retry}>Try again</button>}</div>; }

function AppShell({ page, setPage, onLogout, children, user }) { return <div className="app-shell"><aside><div className="brand"><span>✦</span> AETHERA</div><p className="workspace-label">WORKSPACE</p><nav>{navItems.map(([id, label]) => <button className={page === id ? 'active' : ''} onClick={() => setPage(id)} key={id}><span>{id === 'dashboard' ? '⌂' : id === 'workspaces' ? '▦' : id === 'shared' ? '↗' : '◎'}</span>{label}</button>)}</nav><div className="sidebar-bottom"><div className="user-chip"><div>{user?.full_name?.slice(0, 1) || 'A'}</div><span>{user?.full_name || 'Loading…'}<small>{user?.email || ''}</small></span></div><button className="logout" onClick={onLogout}>↪ Log out</button></div></aside><section className="main-area"><header><div><p className="eyebrow">AETHERA / {page.replace('-', ' ').toUpperCase()}</p><h2>{page === 'workspace' ? 'Workspace' : page === 'shared' ? 'Shared files' : page === 'profile' ? 'Profile & settings' : page[0].toUpperCase() + page.slice(1)}</h2></div><div className="top-status"><span></span> Secure session</div></header>{children}</section></div>; }

function Dashboard({ go }) { const { data: workspaces, loading, error, reload } = useAsync(api.workspaces, []); const { data: shares } = useAsync(api.shares, []);
  if (error) return <ErrorState message={error} retry={reload} />;
  return <div className="page-content"><section className="hero"><div><p className="eyebrow">YOUR SPACE</p><h1>Good to see you.</h1><p>Pick up where you left off or create a new space for your next project.</p></div><button className="button primary" onClick={() => go('workspaces')}>Manage workspaces</button></section><section className="stat-grid"><Stat label="Workspaces" value={loading ? '—' : workspaces.length} /><Stat label="Shared with you" value={shares?.length ?? '—'} /><Stat label="Storage" value="Live data" detail="shown per workspace" /></section><section className="panel"><div className="panel-head"><div><h3>Recent workspaces</h3><p>Spaces you own or collaborate in.</p></div><button className="text-button" onClick={() => go('workspaces')}>View all</button></div>{loading ? <Loading /> : workspaces.length ? <div className="workspace-cards">{workspaces.slice(0, 3).map((workspace) => <WorkspaceCard key={workspace.workspace_id} workspace={workspace} open={() => go('workspace', workspace.workspace_id)} />)}</div> : <Empty title="No workspaces yet" body="Create your first workspace to organize folders and files." action={<button className="button primary" onClick={() => go('workspaces')}>Create workspace</button>} />}</section></div>; }
function Stat({ label, value, detail }) { return <div className="stat"><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</div>; }
function Loading() { return <div className="loading">Loading real AETHERA data…</div>; }
function WorkspaceCard({ workspace, open }) { return <button className="workspace-card" onClick={open}><span className={`color-dot ${workspace.color}`}></span><div><h4>{workspace.workspace_name}</h4><p>{workspace.description || 'No description yet'}</p></div><small>{workspace.member_role || 'OWNER'} · {workspace.visibility}</small></button>; }

function Workspaces({ open }) { const { data, loading, error, reload } = useAsync(api.workspaces, []); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ workspace_name: '', workspace_type: 'PERSONAL', description: '', visibility: 'PRIVATE', color: 'blue' }); const [message, setMessage] = useState('');
  const create = async (e) => { e.preventDefault(); setMessage(''); try { const workspace = await api.createWorkspace(form); setShowForm(false); open('workspace', workspace.workspace_id); } catch (err) { setMessage(err.message); } };
  return <div className="page-content"><div className="page-actions"><p className="muted">Create spaces for projects, teams, and private work.</p><button className="button primary" onClick={() => setShowForm(!showForm)}>+ New workspace</button></div>{showForm && <form className="inline-form" onSubmit={create}><Field label="Workspace name" value={form.workspace_name} onChange={(workspace_name) => setForm({ ...form, workspace_name })} required /><label className="field"><span>Type</span><select value={form.workspace_type} onChange={(e) => setForm({ ...form, workspace_type: e.target.value })}><option value="PERSONAL">Personal</option><option value="INSTITUTION">Institution</option></select></label><Field label="Description (optional)" value={form.description} onChange={(description) => setForm({ ...form, description })} /><label className="field"><span>Visibility</span><select value={form.visibility} onChange={(e) => setForm({ ...form, visibility: e.target.value })}><option value="PRIVATE">Private</option><option value="SHARED">Shared</option></select></label>{message && <div className="notice">{message}</div>}<button className="button primary">Create workspace</button></form>}{error ? <ErrorState message={error} retry={reload} /> : loading ? <Loading /> : data.length ? <div className="workspace-list">{data.map((workspace) => <WorkspaceCard key={workspace.workspace_id} workspace={workspace} open={() => open('workspace', workspace.workspace_id)} />)}</div> : <Empty title="No workspaces yet" body="Your workspace list is empty in the backend." />}</div>; }

function WorkspaceDetail({ workspaceId, back, go }) { const { data: workspace, loading, error, reload } = useAsync(() => api.workspace(workspaceId), [workspaceId]); const foldersState = useAsync(() => api.folders(workspaceId), [workspaceId]); const membersState = useAsync(() => api.workspaceMembers(workspaceId), [workspaceId]); const [folderName, setFolderName] = useState(''); const [member, setMember] = useState({ user_id: '', role: 'VIEWER' }); const [notice, setNotice] = useState('');
  const createFolder = async (event) => { event.preventDefault(); try { await api.createFolder({ workspace_id: workspaceId, folder_name: folderName, color: 'blue' }); setFolderName(''); foldersState.reload(); } catch (err) { setNotice(err.message); } };
  const addMember = async (event) => { event.preventDefault(); try { await api.addWorkspaceMember(workspaceId, { user_id: Number(member.user_id), role: member.role }); setMember({ user_id: '', role: 'VIEWER' }); membersState.reload(); } catch (err) { setNotice(err.message); } };
  if (error) return <ErrorState message={error} retry={reload} />; if (loading) return <Loading />;
  return <div className="page-content"><button className="back" onClick={back}>← All workspaces</button><section className="workspace-header"><span className={`big-dot ${workspace.color}`}></span><div><p className="eyebrow">{workspace.workspace_type} · {workspace.visibility}</p><h1>{workspace.workspace_name}</h1><p>{workspace.description || 'No description provided.'}</p></div><div className="storage"><span>Storage</span><strong>{formatBytes(workspace.storage_used)} <small>of {workspace.storage_limit ? formatBytes(workspace.storage_limit) : 'unlimited'}</small></strong></div></section><section className="panel"><div className="panel-head"><div><h3>Folders</h3><p>Open a folder to view its actual files.</p></div></div><form className="compact-form" onSubmit={createFolder}><input placeholder="New folder name" value={folderName} onChange={(e) => setFolderName(e.target.value)} required /><button className="button secondary">Add folder</button></form>{notice && <div className="notice">{notice}</div>}{foldersState.error ? <ErrorState message={foldersState.error} retry={foldersState.reload} /> : foldersState.loading ? <Loading /> : foldersState.data.length ? <div className="folder-grid">{foldersState.data.map((folder) => <button className="folder-card" key={folder.folder_id} onClick={() => go('folder', folder.folder_id, workspace)}><span>▰</span><b>{folder.folder_name}</b><small>{folder.description || 'Folder'}</small></button>)}</div> : <Empty title="This workspace is empty" body="Create a folder to begin organizing files." />}</section></div>; }

 function FolderBrowser({ folderId, workspace, back, go }) { const { data: folder, loading: folderLoading, error: folderError } = useAsync(() => api.folders(workspace.workspace_id).then((all) => all.find((item) => item.folder_id === folderId)), [folderId, workspace.workspace_id]); const filesState = useAsync(() => api.files(folderId), [folderId]); const [selected, setSelected] = useState(null); const [uploading, setUploading] = useState(false);
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); try { await api.uploadFile(folderId, file); filesState.reload(); } catch (error) { alert(error.message); } finally { setUploading(false); event.target.value = ''; } };
  useEffect(() => { const button = document.querySelector('.browser-title .button.secondary'); if (!button) return undefined; const input = document.createElement('input'); input.type = 'file'; input.hidden = true; input.onchange = upload; const openPicker = (event) => { event.stopPropagation(); input.click(); }; button.textContent = uploading ? 'Uploading…' : 'Upload file'; button.addEventListener('click', openPicker, true); button.appendChild(input); return () => { button.removeEventListener('click', openPicker, true); input.remove(); }; }, [upload, uploading]);
  if (folderError) return <ErrorState message={folderError} />; if (folderLoading) return <Loading />;
  return <div className="page-content"><button className="back" onClick={back}>← {workspace.workspace_name}</button><section className="browser-title"><div><p className="eyebrow">FOLDER</p><h1>▰ {folder?.folder_name || 'Folder'}</h1><p>{folder?.description || 'Files stored in this folder.'}</p></div><button className="button secondary" onClick={() => alert('The current backend exposes file metadata APIs only; it does not provide a binary file-upload endpoint.')}>Upload unavailable</button></section><section className="panel"><div className="panel-head"><div><h3>Files</h3><p>File records returned by the AETHERA API.</p></div></div>{filesState.error ? <ErrorState message={filesState.error} retry={filesState.reload} /> : filesState.loading ? <Loading /> : filesState.data.length ? <div className="file-table"><div className="table-head"><span>Name</span><span>Type</span><span>Size</span><span>Updated</span><span></span></div>{filesState.data.map((file) => <div className="file-row" key={file.file_id}><span><b>▧</b> {file.file_name}</span><span>{file.mime_type || file.file_extension || '—'}</span><span>{formatBytes(file.file_size)}</span><span>{formatDate(file.updated_at)}</span><button className="text-button" onClick={() => setSelected(file)}>Share</button></div>)}</div> : <Empty title="No files in this folder" body="No file records have been created in the backend for this folder." />}</section>{selected && <ShareDialog file={selected} close={() => setSelected(null)} onCreated={() => go('shared')} />}</div>; }

function ShareDialog({ file, close, onCreated }) { const [form, setForm] = useState({ share_type: 'LINK', permission: 'VIEW', shared_with: '', expires_at: '' }); const [error, setError] = useState(''); const submit = async (e) => { e.preventDefault(); try { const payload = { file_id: file.file_id, share_type: form.share_type, permission: form.permission }; if (form.share_type === 'PRIVATE' && form.shared_with) payload.shared_with = Number(form.shared_with); if (form.expires_at) payload.expires_at = new Date(form.expires_at).toISOString(); await api.createShare(payload); onCreated(); } catch (err) { setError(err.message); } };
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><button type="button" className="modal-close" onClick={close}>×</button><p className="eyebrow">SHARE FILE</p><h3>{file.file_name}</h3><label className="field"><span>Share type</span><select value={form.share_type} onChange={(e) => setForm({ ...form, share_type: e.target.value })}><option value="LINK">Link</option><option value="PUBLIC">Public</option><option value="PRIVATE">Private</option></select></label>{form.share_type === 'PRIVATE' && <Field label="Recipient user ID" type="number" value={form.shared_with} onChange={(shared_with) => setForm({ ...form, shared_with })} required />}<label className="field"><span>Permission</span><select value={form.permission} onChange={(e) => setForm({ ...form, permission: e.target.value })}><option value="VIEW">View</option><option value="EDIT">Edit</option></select></label><label className="field"><span>Expiration</span><select value={form.expires_at ? 'date' : 'never'} onChange={(e) => setForm({ ...form, expires_at: e.target.value === 'never' ? '' : form.expires_at || new Date(Date.now() + 86400000).toISOString().slice(0, 16) })}><option value="never">Never</option><option value="date">Expiration date/time</option></select></label>{form.expires_at && <Field label="Expires at" type="datetime-local" value={form.expires_at} onChange={(expires_at) => setForm({ ...form, expires_at })} required />}{error && <div className="notice">{error}</div>}<button className="button primary">Create share</button></form></div>; }

function SharedFiles() { const state = useAsync(api.shares, []); const revoke = async (id) => { if (!window.confirm('Revoke this share?')) return; try { await api.revokeShare(id); state.reload(); } catch (error) { alert(error.message); } };
  return <div className="page-content"><section className="panel"><div className="panel-head"><div><h3>Shared files</h3><p>Shares available to you or created by you.</p></div></div>{state.error ? <ErrorState message={state.error} retry={state.reload} /> : state.loading ? <Loading /> : state.data.length ? <div className="file-table"><div className="table-head"><span>File ID</span><span>Access</span><span>Shared with</span><span>Created</span><span></span></div>{state.data.map((share) => <div className="file-row" key={share.share_id}><span>File #{share.file_id}</span><span>{share.share_type} · {share.permission}</span><span>{share.shared_with ? `User #${share.shared_with}` : 'Link / public'}</span><span>{formatDate(share.created_at)}</span><button className="text-button danger" onClick={() => revoke(share.share_id)}>Revoke</button></div>)}</div> : <Empty title="No shared files yet" body="When a file is shared through AETHERA, it will appear here." />}</section></div>; }

function Profile({ onUserChange }) { const state = useAsync(api.me, []); const [editing, setEditing] = useState(false); const [form, setForm] = useState(null); const [message, setMessage] = useState(''); useEffect(() => { if (state.data) setForm({ full_name: state.data.full_name, username: state.data.username, email: state.data.email, bio: state.data.bio || '' }); }, [state.data]); const save = async (e) => { e.preventDefault(); try { const user = await api.updateMe(form); onUserChange(user); setEditing(false); setMessage('Profile saved.'); state.reload(); } catch (err) { setMessage(err.message); } };
  if (state.error) return <ErrorState message={state.error} retry={state.reload} />; if (state.loading || !form) return <Loading />; const user = state.data;
  return <div className="page-content profile"><section className="profile-card"><div className="avatar">{user.full_name.slice(0, 1)}</div><div><h3>{user.full_name}</h3><p>@{user.username} · {user.account_type}</p><p className="muted">{user.email}</p></div><button className="button secondary" onClick={() => setEditing(!editing)}>{editing ? 'Cancel' : 'Edit profile'}</button></section>{message && <div className="notice success">{message}</div>}{editing && <form className="inline-form" onSubmit={save}><Field label="Full name" value={form.full_name} onChange={(full_name) => setForm({ ...form, full_name })} required /><Field label="Username" value={form.username} onChange={(username) => setForm({ ...form, username })} required /><Field label="Email" type="email" value={form.email} onChange={(email) => setForm({ ...form, email })} required /><label className="field"><span>Bio</span><textarea value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} /></label><button className="button primary">Save changes</button></form>}<section className="stat-grid"><Stat label="Storage used" value={formatBytes(user.storage_used)} /><Stat label="Storage limit" value={user.storage_limit ? formatBytes(user.storage_limit) : 'Unlimited'} /><Stat label="Email" value={user.email_verified ? 'Verified' : 'Unverified'} /></section></div>; }

export default function App() { const [authenticated, setAuthenticated] = useState(Boolean(authStore.token)); const [page, setPage] = useState('dashboard'); const [params, setParams] = useState({}); const [user, setUser] = useState(null); const [oauthError, setOauthError] = useState(''); const googleHandoffStarted = useRef(false); const me = useAsync(() => authenticated ? api.me() : Promise.resolve(null), [authenticated]); useEffect(() => { if (me.data) setUser(me.data); }, [me.data]); useEffect(() => { const handler = () => setAuthenticated(false); window.addEventListener('aethera:unauthorized', handler); return () => window.removeEventListener('aethera:unauthorized', handler); }, []); useEffect(() => { const handoffCode = new URLSearchParams(window.location.search).get('oauth_code'); if (!handoffCode || googleHandoffStarted.current) return; googleHandoffStarted.current = true; api.exchangeGoogleOAuthCode(handoffCode).then((tokens) => { authStore.set(tokens); setAuthenticated(true); }).catch((error) => setOauthError(error.message || 'Google sign-in could not be completed.')).finally(() => window.history.replaceState({}, document.title, window.location.pathname)); }, []);
  const go = (next, id, workspace) => { setPage(next); setParams({ id, workspace }); }; const logout = async () => { try { await api.logout(); } catch (_) {} authStore.clear(); setAuthenticated(false); setPage('dashboard'); };
  if (!authenticated) return <AuthScreen onAuthenticated={() => setAuthenticated(true)} oauthError={oauthError} />;
  let content = page === 'dashboard' ? <Dashboard go={go} /> : page === 'workspaces' ? <Workspaces open={go} /> : page === 'workspace' ? <WorkspaceDetail workspaceId={params.id} back={() => go('workspaces')} go={go} /> : page === 'folder' ? <FolderBrowser folderId={params.id} workspace={params.workspace} back={() => go('workspace', params.workspace.workspace_id)} go={go} /> : page === 'shared' ? <SharedFiles /> : <Profile onUserChange={setUser} />;
  return <AppShell page={page} setPage={setPage} onLogout={logout} user={user}>{content}</AppShell>;
}
